apiVersion: apps/v1
kind: weathers
metadata:
  name: weathers
  labels:
    app: weathers
spec:
  replicas: 1   # pod
  selector:
    matchLabels:
      app: weathers
  template:
    metadata:
      labels:
        app: weathers
    spec:
      containers:
        - name: weathers
          image: seoyerin307/weathers
          ports:
            - containerPort: 8000 # container port(pod port)