apiVersion : apps/v1
kind: Deployment
metadata:
  name: quake
  labels:
    app: quake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quake
  template:
    metadata:
      labels:
        app: quake
    spec:
      containers:
        - name: quake
          image: pengbai/docker-supermario
---
apiVersion: v1
kind: Service
metadata:
  name: quake
spec:
  selector:
    app: quake
  ports:
    - name: connect
      port: 80
      protocal: TCP
      targetPort: 80
      nodePort: 30000
    - name: multiplay
      port: 27960
      protocal: TCP
      targetPort: 27960
      nodePort: 30100
  type: LoadBalancer
  externalIPs:
    - 3.37.129.19
