apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote
  labels:
    app: remote
spec:
  replicas: 1   # pod
  selector:
    matchLabels:
      app: remote
  template:
    metadata:
      labels:
        app: remote
    spec:
      containers:
        - name: remote
          image: seoyerin307/remote
          ports:
            - containerPort: 8000 # container port(pod port)